module.exports = [{ en:'Knowledge', ru:'Знания' },
    { en: 'Money', ru: 'Деньги' },
    { en: 'Food', ru: 'Пища' },
    { en: 'Wood', ru: 'Древесина' },
    { en: 'Metal', ru: 'Металл' },
    { en: 'Fuel', ru: 'Топливо' },
    { en: 'Granite', ru: 'Гранит' },
    { en: 'Pack animals', ru: 'Вьючные животные' },
    { en: 'Sulfur', ru: 'Сера' },
    { en: 'Aluminum', ru: 'Алюминий' },
    { en: 'Uranium', ru: 'Уран' },
    { en: 'Fruit', ru: 'Фрукты' },
    { en: 'Corn', ru: 'Кукуруза' },
    { en: 'Wheat', ru: 'Пшеница' },
    { en: 'Rice', ru: 'Рис' },
    { en: 'Fish', ru: 'Рыба' },
    { en: 'Meat', ru: 'Мясо' },
    { en: 'Wine', ru: 'Вино' },
    { en: 'Jewels', ru: 'Драгоценности' },
    { en: 'Clothes', ru: 'Одежда'},
    { en: 'Music', ru: 'Музыка'},
    { en: 'Movies', ru: 'Фильмы'},
    { en: 'Books', ru:'Книги' }
]